name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 12.18.4

jobs:
  checks:
    name: Checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Linter
        run: yarn lint

      - name: Build
        run: yarn build
